######################################################################
# Automatically generated by qmake (2.01a) Sat Jul 11 14:14:43 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MainWindow.cpp
SOURCES += Main.cpp MainWindow.cpp
