######################################################################
# Automatically generated by qmake (2.01a) Sun Jul 12 13:38:09 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += MainWindow.h MainWindow.cpp toggle_file.cpp
SOURCES += Main.cpp MainWindow.cpp toggle_file.cpp
